export type Events =
  | "USER_MESSAGE"
  | "MESSAGE_STREAM_START"
  | "MESSAGE_STREAM_END"
  | "THINKING_START"
  | "THINKING_END"
  | "ANSWERING_START"
  | "ANSWERING_END"
  | "LIMIT_REACHED"
  | "AVATAR_SLEEP"
  | "AVATAR_WAKE_UP";
